name: Scoop Manifest Validation

on:
  push:
    paths:
      - "phase.json"
  pull_request:

jobs:
  manifest-validation:
    name: Validate Scoop Manifest
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Scoop Package Manager
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm get.scoop.sh | iex
        shell: pwsh

      - name: Add Scoop to PATH
        run: echo "${env:USERPROFILE}\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Install and verify phase-cli
        run: |
          scoop install ${{ github.workspace }}\phase.json
          $content = Get-Content ${{ github.workspace }}\phase.json | ConvertFrom-Json
          $expected = $content.version
          $actual = phase --version
          if ($actual -ne $expected) {
            throw "Version mismatch: Expected $expected, but found $actual"
          }
        shell: pwsh
