name: Scoop Manifest Validation

on:
  push:
    paths:
      - "phase.json"
  pull_request:
    paths:
      - "phase.json"

jobs:
  manifest-validation:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Scoop Package Manager
        run: iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        shell: pwsh

      - name: Update PATH and Install Scoop App
        run: |
          ls
          ls -l
          $env:Path += ";$env:USERPROFILE\scoop\shims"
          Write-Output "Updated PATH: $env:Path"
          scoop install ./phase.json
          Write-Output "Installed applications:"
          scoop list
          Write-Output "Looking for 'phase' command:"
          Get-Command phase
        shell: pwsh

      - name: Verify phase-cli Version
        run: |
          $content = Get-Content phase.json | ConvertFrom-Json
          $expected = $content.version
          $actual = phase --version
          Write-Output "Expected version: $expected"
          Write-Output "Actual version: $actual"
          if ($actual -ne $expected) {
            throw "Mismatch: Expected $expected, but found $actual"
          }
        shell: pwsh
