name: Scoop Manifest Validation

on:
  push:
    paths:
      - "phase.json"
  pull_request:
    paths:
      - "phase.json"

jobs:
  manifest-validation:
    name: Validate Scoop Manifest
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Scoop Package Manager
        run: iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
        shell: pwsh

      - name: Install Scoop and Configure
        run: |
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          $env:Path += ";$env:USERPROFILE\scoop\shims"
          scoop install ./phase.json
        shell: pwsh

      - name: Determine Manifest Version
        run: |
          $content = Get-Content phase.json | ConvertFrom-Json
          echo "VERSION=${content.version}" >> $GITHUB_ENV

      - name: Verify CLI Version
        run: |
          $env:Path += ";$env:USERPROFILE\scoop\shims"
          $expected = $env:VERSION
          $actual = & phase --version
          if ($actual -ne $expected) {
            throw "Mismatch: Expected $expected, but found $actual"
          }
        shell: pwsh
